# Generated by Django 4.1.5 on 2023-01-13 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=1, verbose_name='Роль')),
                ('surname', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('soname', models.CharField(blank=True, max_length=64, verbose_name='Отчество')),
                ('phone', models.CharField(blank=True, max_length=16, unique=True, verbose_name='Номер телефона')),
                ('avatar', models.ImageField(default='/no-image.png', upload_to='avatars/', verbose_name='Аватар')),
                ('tgID', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Телеграм')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('wage', models.IntegerField(blank=True, null=True, verbose_name='Оклад')),
                ('cost', models.IntegerField(blank=True, null=True, verbose_name='Ставка за групповое занятие')),
                ('cost_individual', models.IntegerField(blank=True, null=True, verbose_name='Ставка за индивидуальное занятие')),
                ('cost_for_student', models.IntegerField(blank=True, null=True, verbose_name='Стоимость индив. для студента')),
                ('agent_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Имя представителя')),
                ('agent_phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='Телефон представителя')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('is_deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['surname'],
            },
        ),
    ]
